### ISSUE TITLE
Eclair do not follow peer IP changes

### ISSUE THREAD

**Issue by slush0** [ACINQ/eclair-mobile#125]
Eclair seems to do not follow updates of IP addresses of nodes. I had to change ip address of my node "ln1.satoshilabs.com", but Eclair didn't reflect such change and channel appear "OFFLINE" even after 14 days of such IP change.

Please implement updating of IP address, this seems to bring unnecessary downtime and running costs for users when infrastructure changes are required.

**Comment by pm47** [comment]
This is related to https://github.com/ACINQ/eclair/issues/471.

Unfortunately on eclair-wallet things are a bit more complicated because we don't have the `node_announcement`s when sync the routing table with channel queries.

 @dpad85 At the very least we should allow users to manually update the ip though (e.g. by scanning a qr code).

**Comment by STAWKEYE** [comment]
So you're ln1.satoshilabs.com.... haha. I was wondering what happened to ya! Should I just force-close the channel or is there a way to sort this out without reopening channels?

**Comment by STAWKEYE** [comment]
Sorry to come back here like I'm stalking your thread, but it appears you're back online now? If you fixed the IP issue please let me know b/c I have yet to restart my router since creating LN node and I'm wondering if I'll screw the whole thing up someday if I get a new IP addy assigned to my PC (I am using the DHCP or whatever feature of my router, but not sure if that's adequate.)
