### ISSUE TITLE
Launching via URI fails on "cold start"

### ISSUE THREAD

**Issue by bithobbes** [ACINQ/eclair-mobile#131]
With the app closed (not just in background, e.g. tap open apps button and swipe it away) and starting a LN payment through clicking a payment URL (e.g. by clicking the QR code here https://jochen-hoenicke.de/lightning/ ) and entering the unlock code quickly (or not really slow at least) Eclair fails with "None of your Lightning channels has enough balance to send this payment". Once the app is launched clicking the QR code works as expected and brings up the pay window.

**Comment by dpad85** [comment]
The control checking the channels' availability fails because the channels have not established a connection with their peers yet, and as such there are no channels ready to pay. It is technically correct but obviously poor UX.

We can either:
- have a softer control in the case of a cold start and take the chance to send the payment even if it could fail.
- wait for the channels to go to NORMAL. I think this option would be worse UX-wise and could bring bugs.

Thanks

**Comment by bithobbes** [comment]
Maybe the payment window or the payment button could wait for the channels and display a message "waiting for channel connection" or something as long as things are not ready.

**Comment by dpad85** [comment]
The `pay` button will now be disabled when the channels are offline which should solve most of the cold start failures. Thanks for the feedback.

**Comment by bithobbes** [comment]
Though I tried several times could only see it once so far and it worked nicely. Thanks a lot!
