### ISSUE TITLE
Error: Payment amount is not valid

### ISSUE THREAD

**Issue by dpad85** [ACINQ/eclair-mobile#137]
This issue was originally opened by @Kixunil on the [eclair repository](https://github.com/ACINQ/eclair/issues/785). Below is the original issue description.

---

On chain payment is impossible due to "invalid" amount, while I see no reason for invalidity of the amount (wallet has larger balance and there are exactly 8 decimal places).

Expected behaviour: The on chain payment is sent after clicking "Pay"

What actually happened: When clicking Pay, the wallet refuses to send the transaction with error message "Payment amount is not valid."

I tried these steps three times and I hit the bug every time:

1. Make sure you have enough coins in the wallet (0.9 in my case)
2. Make a QR code in the form bitcoin:2addr?amount=0.00036185
3. Scan the QR code with testnet wallet (not tested on mainnet)
4. Click Pay

Testnet version 0.3.13 from Google Play

Android 5.0.2
HTC SDK 6.55

**Comment by dpad85** [comment]
@Kixunil I've followed the steps you've given and have not been able to reproduce this issue.

From what you describe, there is a problem when parsing the amount parameter in the URI and feeding it to the pay window. I've got a few questions:

- After scanning the QR code, is the amount field correctly filled in? Do you see any non numeric character, such as a `<space>` blank character? Could you copy the value in the field and paste it here?
- What language are you using in Android ? You can check that in the device settings > Language & Keyboards > Languages. There might be a localization issue when converting the parsed amount from the URI into a numeric amount that the wallet can use.

**Comment by Kixunil** [comment]
Sorry for the mistake.

* After scanning the QR code, is the amount field correctly filled in?

Stupid me, I should have thought about it before. The problem is I'm using Slovak localization which uses comma (`,`) instead of dot (`.`) as a separator between whole and decimal part of the number. So after scanning QR code, which correctly uses dot, the number shown uses comma. When I edited the amount by replacing comma with dot, it worked.

**Comment by ndeet** [comment]
Hi @dpad85 

can confirm this happening on my localised (in my case German) Android. The on-chain payment amount has a `,` decimal separator instead of `.` which makes payment amount invalid. On LN this works correctly, only the on-chain payment amount is wrong.

The QR code has the following data encoded (amount correct with `.` as separator:
`bitcoin:mhznGV4xQvU48fNjBwSzbsb1z4WdZPGbFD?amount=0.0068308`

This results in this wrong amount:
![image](https://user-images.githubusercontent.com/1136761/50711125-6b593980-106d-11e9-82d9-e7eed5eadd99.png)

You can test yourself here by buying the "Test BTC on-chain" product on the top left:
https://testnet.demo.btcpay.tech/apps/3z9BDhDXvtVDD59rjk4sQpqLwb17/pos

**Comment by githorray** [comment]
I just hit it too. bitcoin:{address removed}?amount=0.017913

![screenshot_20190113-125141_2](https://user-images.githubusercontent.com/39980780/51165019-cf83c500-18d9-11e9-9793-d3acdca75f0c.png)

**Comment by molxyz** [comment]
Trying with this site https://example.coingate.com/ also got the same error. Version 0.3.15.

**Comment by dpad85** [comment]
Reproduced and fixed in the next release. Thanks!
