### ISSUE TITLE
Cannot connect to specific ElectrumX server

### ISSUE THREAD

**Issue by Stadicus** [ACINQ/eclair-mobile#141]
The possibility to connect to my own Electrum backend is a great addition and could make Electrum my go-to wallet, also for on-chain funds.

I am struggling to connect to my own server, however, an full ElectrumX node that runs with SSL with a self-signed certificate. No problem connecting with Electrum desktop or mobile wallet, or the Bitbox hardware wallet.

First, Eclair crashed and I had to completely reinstall, losing all open channels in the progress (despite recovery seed & channel backup). Now, the app is set up but shows constantly the following error message: 
```
Establishing connection with electrum.stadicus.com:50002...
```

You emphasize the need for a valid certificate". Does that mean that a self-signed SSL certificate is ok, or does it need to be a certificate from a trusted issuer like LetsEncrypt?

**Comment by pm47** [comment]
> Does that mean that a self-signed SSL certificate is ok, or does it need to be a certificate from a trusted issuer like LetsEncrypt?

A self-signed certificate is *not* ok, and yes LetsEncrypt would work. The rationale is that if you choose to connect to a specific server, you probably want to be sure that you cannot be easily MITMed. Otherwise why not connect to a public server instead?

> Eclair crashed and I had to completely reinstall, losing all open channels in the progress (despite recovery seed & channel backup)

Please provide more details, this warrants an investigation, as there is no known issue with backup/restore. How did you lose your seed and backup?

**Comment by Stadicus** [comment]
Thanks for the clarification regarding the certificate, I'll set up a real certificate.

Regarding my crash, I am not sure how to provide additional details. The events were like this:
* Running Eclair Mobile with a few bucks in open channels, no on-chain funds, chain backup to Google Drive enabled
* Configuration of custom Electrum server (I think I did **not specify the port**, just `electrum.stadicus.com`)
* Eclair Mobile restarts, get's stuck on initial screen (before PIN request), I let it stay for hours, regularly checking back into the app. No amount of restart resolved the issue.
* Uninstall Eclair Mobile
* Reinstall, recover from seed (I have no doubt that the on-chain funds would be back). Channels are gone, last backup shown by the app is from January 6h 2019. 

What information can I provide to improve Eclair? I can send you my seed, channel backup etc. privately (does not contain  funds anymore).

**Comment by pm47** [comment]
The cause of the crash is most certainly the fact that you didn't specify a port. This bug was fixed with 445ff97aceec148423b4455d2da11b9a47d3d20b and released in 0.3.15.

> Channels are gone, last backup shown by the app is from January 6h 2019.

Did your on-chain transactions appear in the history? Is it the time you attempted the restore?

**Comment by Stadicus** [comment]
Yes, this seems to be the point where I tried to connect to my own Electrum server. The 6/01/2019 seems to fit your [tweet](https://twitter.com/acinq_co/status/1081198576745803777) regarding the Electrum server feature on the 4th. :-)

Past on-chain transactions show up as expected.

**Comment by Stadicus** [comment]
Where is the backup actually stored? I cannot find it on my google drive.

**Comment by dpad85** [comment]
Hi, I've got a few questions:

* When you restored your seed, did you get a window prompting you to restore the backup from google drive? This window tells something like:
```
If you already used Eclair Mobile with this seed, you may have a backup on Google Drive.
Do you want to attempt to restore these channels?
```
* If you did get this window, can you describe what you did and what happened? 
If I guess right, you tried to restore your backup, the app asked for permissions to access your Google drive account, and for **some reasons**, did not find any backup. Now there can be many reasons, like sync issues with Drive, or permissions that were not correctly set. Anyway you've skipped this restore step, and after this point, the app will not provide any way to restore Drive backup.

Good thing is that the app can now find your backup on Drive, dating from 2018/01/06. I think that the app needs a way to restore a backup even after the user has skipped the restore step. I'm going to give you an APK which does just that, in the mean time, do not open any channels, otherwise the existing backup on Drive will be overwritten.

> Where is the backup actually stored? I cannot find it on my google drive.

The backup is stored in the hidden App Data folder of your Drive account. You cannot access files on this app folder to prevent any tampering.

**Comment by dpad85** [comment]
@Stadicus Please reach me out on gitter or by email when you want the APK with the restore option.

**Comment by Stadicus** [comment]
@dpad85, no, I did not get this window prompting me to restore the backup (I'm pretty sure, 90%?). Unfortunately, I already opened new channels, so the backup is probably gone. No big deal, just a few bucks.

**Comment by Stadicus** [comment]
Closing this issue, unless you have additional questions.
