### ISSUE TITLE
Cap lightning fees with maximum value, not merely percentage

### ISSUE THREAD

**Issue by andronoob** [ACINQ/eclair-mobile#142]
Might be dupelicate with #36.

A lot of LN nodes has a base routing fee, e.g. 1sat/payment. Therefore, if the user trys to pay an extreme small amount, currently the payment usually fail, due to the 3% limit. If the user simply turn off this limit, it seems that he's taking some risk of being accidentally charged with extreme high fees.

I think the fee capping policy should be more sophiscated, e.g. for payment smaller than 1000sat, cap the fee with a fixed 30sat limit.

**Comment by dpad85** [comment]
Hello,

This issue has been fixed with the `v0.3.19` release, which is available on mainnet and testnet. If the fee is below 21 satoshi, the fee protection mechanism will not reject the payment.

You can take a look at @araspitzu PR for more information: https://github.com/ACINQ/eclair/pull/844

**Comment by fjdone** [comment]
I end up paying 90 sats for sending 10k sats that is a fee of 0.9% too high, lower the percentage fee to 0.1% instead if fucking %3 unless you all people in Lightning Network development team just want to be another PayPal with Bitcoin name on top of it

**Comment by fjdone** [comment]
Eclair mobile 0.4.9 need to lower the fees

**Comment by fjdone** [comment]
Eclair mobile needs to create a option where it tells us before we send the payment how much will be the fee. You don't do the job first and then hold your boss for ramson, Eclair mobile is doing just that with your Bitcoin when the app doesn't tell you the fees first before sending the tx. That is ramson and this should be ilegal, You Say your fees before the word is done but after it

**Comment by pm47** [comment]
So you have paid a 0.0072 USD fee, SFYL. This fee hasn't gone to us but to whoever has routed the payment.

The 3% limit is not a target fee but a protection. By the way there is a tolerance for small amounts so you may be paying more than >100% fees for 1 sat payments. How about that?

It's not easy to know beforehand what the fee will be, because most of the time we have to try several payment routes before finding one that works. UX would be terrible if we showed a popup ten times in a row. Trampoline will help but it will also have to be pessimistic with fee calculations.

Strong language, accusing us of ransoming users => blocked.
