### ISSUE TITLE
Why my bitcoin wallet is changed 

### ISSUE THREAD

**Issue by kasadawa** [ACINQ/eclair-mobile#145]
Yesterday I send BTC to my eclair bitcoin wallet, but today I am seeing that today the wallet address is changed , and the funds are not in the app. On the bottom it says "Syncing from btc.smsys.me:995..." . 
Can you explain to me where my funds have gone ?

P.S. The funds were received :) , but why the BTC  address has changed  ?

**Comment by dpad85** [comment]
Hello,

`Syncing from btc.smsys.me:995...` This message means that the wallet is still catching up with the bitcoin blockchain, it can take some time.

For the address change: Eclair mobile is a deterministic wallet and by design generates a new address every time you receive a transaction. This is intended. Using the same address again and again would be bad for your privacy.

You can read more about this here: https://en.bitcoin.it/wiki/Address_reuse
