### ISSUE TITLE
[Question] [Testnet] No receivable btc

### ISSUE THREAD

**Issue by ParmuSingh** [ACINQ/eclair-mobile#158]
I've asked this on reddit as well: https://www.reddit.com/r/lightningnetwork/comments/ay1thg/can_terminal_nodes_receive_payments/?utm_medium=android_app&utm_source=share

I wanted to test receive functionality so I tried the testnet app. I made a channel to ACINQ but it says my receive capacity is 0. Why is that? Does this mean terminal nodes cannot receive lightning payments?

**Comment by dpad85** [comment]
Hello,

Terminal nodes can receive payments, as long as they have enough incoming capacity, that is their channels are balanced in such a way that these channels can transport funds from the counterpart to them.

For example, if you open a channel for `10 mBTC`: you'll be able to send `10 mBTC`, and receive `0 mBTC` since all the balance is on your side.

Then you send `3 mBTC`, the balance will change to `7 mBTC` on your side, and `3 mBTC` on the counterpart's side. You'll be able to receive `3 mBTC`.

Obviously this is not perfect since you have to pay first to be able to receive. This is why the LN specs propose a Dual funding mechanism (see https://github.com/lightningnetwork/lightning-rfc/pull/184) which allow opening balanced channels. This is not ready yet, so in the meantime, some nodes propose a liquidity mechanism where they open a channel to you (hence giving you inbound capacity). For example, our testnet node offer such a solution, for a fee (see : https://medium.com/@ACINQ/enabling-receive-on-eclair-mobile-2e1b87bd1e3a#3865).

**Comment by ParmuSingh** [comment]
I get it now! I was trying out in testnet and turns out I didn't tick "request liquidity.." i didn't not know about the LIP (Lightning improvement proposal?). Thanks.
