### ISSUE TITLE
"Unable to watch your channels" when I do not have any

### ISSUE THREAD

**Issue by syrop** [ACINQ/eclair-mobile#170]
1. I have no open channels
2. I haven't been using Eclair for several days
3. I received a warning "unable to watch your channels", and subsequently "Eclair Mobile needs access to the internet at least once every two weeks to protect your funds".

I know the meaning. It is supposed to protect my channels against uncooperative closing by the other party. The problem is that I do not have any open channels, and this message is confusing and even creepy.

Please consider disabling this message for users who do not have any open channels, or at least automatically connecting to the internet every 24 hours using a WorkManager.

(Please mark this issue as an enchnancement as opposed to a bug).

**Comment by dpad85** [comment]
Thanks for reporting this.

We are already using a `WorkManager` for this, and we could indeed prevent the job from running if there is no connection, but the idea is to display a notification in that very case so that the user is aware of the problem.

Still, there should not be any check if there is nothing to watch, it's confusing for the user, I'll fix this.

For the time being, if you have a recent Android, this notification can be disabled from the application's settings (name is 'Background watcher')

**Comment by syrop** [comment]
I am aware of the way notifications work on Android.

Maybe you could change the wording of the message. Bitcoins are not supposed to disappear if one doesn't connect to the Internet. People have kept their bitcoins in one address for years. It's not clear from the message that it is about the Lightning Network.

**Comment by dpad85** [comment]
I've updated the wording with ce398f2 , the message now reads: 

> To protect the funds in your Lightning channels, Eclair needs to watch the blockchain once in a while, but has been unable to do so the last few days. Make sure that you have a working internet connection.
