### ISSUE TITLE
Mainnet payments failed

### ISSUE THREAD

**Issue by pors** [ACINQ/eclair-mobile#21]
I tried two LN payments to different merchants (blockstream store and hodlmoney) and both attempts failed.

Two screenshots of the payment request and the errors. It is reproducible:

![image 2018-04-06 20 53 45](https://user-images.githubusercontent.com/1078320/38436209-9a339ace-39dc-11e8-8c61-64634468f5df.jpg)

![image 2018-04-06 20 53 49](https://user-images.githubusercontent.com/1078320/38436217-9e55dec8-39dc-11e8-8ed8-bfb6b2c340a1.jpg)

Any idea what is causing this?

**Comment by sstone** [comment]
it could be a liquidity issue (see #14 for example). Have you tried paying for very cheap items on yalls(mainnet) ?

**Comment by pors** [comment]
Yeah, a payment to yalls did work. I wonder if it has to do with liquidity though, or the error messages are a it "off" :)

**Comment by pm47** [comment]
@pors `channel currently unavailable` is typically the kind of errors you will get when a channel in the route can't relay the payment because it is unbalanced. This is a spec requirement: for privacy reasons, channels don't send out details informations about their current balance, because that would leak a lot of information, and open way to probing attacks.

The current state of the network (mostly <$10 channels) doesn't really allow making payments worth $35 like what you are trying to do. The only solution currently would be to open a channel directly with the merchant you are trying to pay. As the network grows that kind of problem will disappear.

**Comment by pors** [comment]
Ah yes, that makes sense. Thanks for explaining!
