### ISSUE TITLE
Where can I find node URIs to paste or scan?

### ISSUE THREAD

**Issue by dbolser** [ACINQ/eclair-mobile#278]
Dumb question I know, but I don't know where to look for nodes to make channels with in Eclair.

BTW, the ACINQ node option says I need > 100,000 and < 50,000,000 sats, but when I try to create a channel I get a (brief) error saying I need > 4,000,000 sats (I think.. I'm adding the commas here for clarity but the error doesn't).

Many thanks,

**Comment by dbolser** [comment]
Sorry, just found this: https://explorer.acinq.co/

* The first one I tried 'failed to connect' e.g. the node was offline I guess.
* The second one I tried had 'incompatible features'

Can I somehow filter the list to those nodes that will work with Eclair mobile?

**Comment by dbolser** [comment]
Not having better luck here:
https://1ml.com/

Nodes there can be:
* On the Tor network
* Have incompatible features
* Have authentication timeout...

Any suggestions on where to get a 'good' list of nodes that Eclair can connect to would be great :-)

**Comment by dbolser** [comment]
I put the node id of my wallet in here
https://terminal.lightning.engineering/

But nothing came up

**Comment by t-bast** [comment]
There is no such thing as a universally "good" list of nodes to connect to, that really depends on your usage patterns.
You should think about how you want to use lightning:

- do you want to mostly pay or receive
- if you're mostly paying, who are you paying more often (then just directly open channels to them)
- otherwise common "hubs" are good choices because they'll let you easily find routes to most places in the network (ACINQ, Breez, LNBig, etc)

**Comment by dbolser** [comment]
OK, forget I said 'good', give me any!

**Comment by t-bast** [comment]
When in doubt, just connect to the ACINQ node as the app suggests?

**Comment by dbolser** [comment]
For some reason the ACINQ node is throwing an error. The UI says I need
>50k <50,000k (or something) but the brief error that pops up when I try to
open a channel says I need > 400k (see OP).
