### ISSUE TITLE
Channel can't be created

### ISSUE THREAD

**Issue by tjthejuggler** [ACINQ/eclair-mobile#285]
I'm not sure what the problem is, maybe there is something I am misunderstanding. For my URI I am using 

<My node ID>@<my phone's public IP>:9735

It seems a bit weird because everything after the @ is the same no matter what device i am using on my home network, but the instructions seem really clear, and i doubt the IP is supposed to be my local IP. Does anyone have any ideas or anything to try? All i want to do is open a channel with a friend, i don't see why it would be more difficult than just sending a transaction. Thanks so much!

**Comment by t-bast** [comment]
Are you trying to connect *to your phone* (or from a phone to another phone)?
That simply will not work because phones don't let you open a port to listen to incoming connections.
It must be the other way around: your phone must connect to a lightning node (running on something else than a phone, which can expose a listening endpoint).
This isn't a limitation of eclair-mobile by the way, just a general limitation of mobile phones.

**Comment by tjthejuggler** [comment]
Thank you very much! I was trying to connect two phone wallets, so your answer explains what is going on, thanks!
