### ISSUE TITLE
Cloning project in Android Studio

### ISSUE THREAD

**Issue by TheRebelOfBabylon** [ACINQ/eclair-mobile#29]
Anybody here manage to do it? I cloned the wallet project, cloned eclair, checked out android branch, built core with maven but I'm having issues with gradle.build where it can't resolve "compile 'fr.acinq.eclair:eclair-core_2.11:0.2-android-SNAPSHOT' ". I have a feeling it's because eclair core needs to be in a folder within the project but I have no idea where to put it.

**Comment by ghost** [comment]
This is a separate library that you need to build before importing the project on Android Studio
https://github.com/ACINQ/eclair-wallet#developers

**Comment by dpad85** [comment]
Your build fails because the eclair-core version in the latest commit on the `android` branch is `0.2-android-beta1`, but the latest commit on the `testnet` branch of eclair wallet requires the version `0.2-android-SNAPSHOT` (the development version of eclair-core for android). Since you have not build the snapshot version, eclair wallet is missing this dependency and can't build.

To fix this, please change `compile 'fr.acinq.eclair:eclair-core_2.11:0.2-android-SNAPSHOT'` by `compile 'fr.acinq.eclair:eclair-core_2.11:0.2-android-beta1'` here:

https://github.com/ACINQ/eclair-wallet/blob/testnet/app/build.gradle#L71

**Comment by TheRebelOfBabylon** [comment]
Perfect changing the dependency worked like a charm! Thanks for the help.
