### ISSUE TITLE
Not enough funds to open channel (but there are)

### ISSUE THREAD

**Issue by dmitryplatonov** [ACINQ/eclair-mobile#6]
Can't open channel. Amount I am opening for is less than my balance. My wallet balance is 0.0014xx BTC.

**Comment by michaelandersonb** [comment]
Same issue here. .0014 btc in wallet. Claims I don't have enough funds for even a .001 channel with slow fee.

**Comment by otaviobonder** [comment]
Same with me. I have 0.0015 and can't open a channel with my node. Tried between 0.001 and 0.0015 and always get a not enough funds message

**Comment by michaelandersonb** [comment]
It seems to opens channel of .0012 btc I had to have .002 btc in the wallet. This is requirement is not clear or mentioned at all from what I can see.

The error message is very useless and doesn't explain the required amount. Why is it required to leave 40% of my funds outside the channel anyway?

**Comment by KibbledJiveElkZoo** [comment]
I have a problem with the program saying there are not enough funds while there appear to be enough funds, too.

I get the message: "None of your Lightning channels has enough balance to send this payment.", when trying to pay a 1,090 microbitcoins (1.09 millibitcoins) BitRefill.com order.  I have a channel with BitRefill's node that has 1,122 microbitcoins (1.122 millibitcoins) in "NORMAL" status.  #confused

**Comment by dpad85** [comment]
Thanks for reporting this issue. This is an old control that check that there is enough onchain funds to pay the fees for the channel funding transaction. At the time, there was no way to customize the funding tx fee, and the network fees were quite high so an arbitrary 1 mBTC leftover was required. This is why you need 2 mBTC in your wallet if you try to open a 1 mBTC channel.

This requirement does not make sense anymore since the wallet now enables you to set up a custom fee for the funding TX. We forgot to remove it.
