### ISSUE TITLE
Payment fails on too high routing fees - even when those are uncapped in Eclair app

### ISSUE THREAD

**Issue by irekzielinski** [ACINQ/eclair-mobile#67]
I have a channel to ACINQ. 
Trying to pay: http://reckless.lnroute.com/

This used to work great in the past, but in last few days there seems to be a regression.
Payment fails. One of the errors is "fee was below the minimum requested by the channel"  - but I disabled fee caps in the app.

**Comment by irekzielinski** [comment]
![screenshot_20180429-103137](https://user-images.githubusercontent.com/19826327/39405212-1a1cbc70-4b99-11e8-85df-7fb68529d979.png)
![screenshot_20180429-103102](https://user-images.githubusercontent.com/19826327/39405214-1e3e8e28-4b99-11e8-8150-4de647fb44c0.png)

**Comment by pm47** [comment]
> This used to work great in the past, but in last few days there seems to be a regression.

Remember that you are testing the whole network, which is dynamic.

> One of the errors is "fee was below the minimum requested by the channel" - but I disabled fee caps in the app.

The error you are encountering isn't related to eclair's uncap fee parameter: here remote node `03a9d` indicates that the fee you were giving to this particular node wasn't enough. In that case that node should attach the required fee to its error message, but since that was already the 10th try, eclair failed the payment.

All other errors are basically unbalanced channels.

**Comment by irekzielinski** [comment]
>Remember that you are testing the whole network, which is dynamic.

Sure - no complains, works amazingly well for beta!


Thanks for the clarification. What about attempt no: 5?
