### ISSUE TITLE
Cannot Connect to rompert.com on Mainnet

### ISSUE THREAD

**Issue by laz666** [ACINQ/eclair-mobile#92]
Hi,

I have been trying to connect to nodes from https://lnmainnet.gaben.win/ on my android phone. I can connect to ACINQ nodes, but not ones entered manually.

I tried the URI '02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b@167.99.50.31:9735', but the app fails to connect. Any idea what may be happening?

PubKey | 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b
Alias | rompert.com🔵
02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b@167.99.50.31:9735

**Comment by sstone** [comment]
Hi, when you open issues please specify which version of eclair and, if possible, details of what you see (error messages, ....). "Cannot connect" is too vague.
Opening a channel to rompert.com does not work because rompert.com does not seem to be working (it never sends the reply to accept_channel), there is nothing we can do.
 
Do you have other examples of nodes you cannot connect to ? Because I can open channels to other nodes (which are not running eclair), bitrefill for example.

**Comment by laz666** [comment]
Hi sstone,

I am using 0.3.4. I tried another node , Lightning.scot and that seems to work. Thanks.

I am also trying to connect the eclair wallet app to my own node and am finding that no one external can connect to my node. Can you point me to any material on how to open a node so others can join? I am running c-lightning on Ubuntu.

Thanks.

**Comment by sstone** [comment]
Ok, I'm closing this since it seems that it was specific to rompert.com.
As for connecting to your own c-lightning node, the generic setup would be to make sure that your LN port is accessible (you probably need to configure your local firewall, your router/internet box, and make sure that you're not just binding to localhost), but for specific advice on c-lightning you can use  #lightning-dev or #c-lightning on IRC, it's very friendly and I'm sure someone will be able to help you.
Thanks
